/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi_andi;

import java.awt.HeadlessException;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.digester.Digester;

/**
 *
 * @author USER
 */
public class FormLaporan extends javax.swing.JFrame {
    Connection koneksi;
    ResultSet hasil;
    PreparedStatement proses;
    /**
     * Creates new form FormLaporan
     */
    public FormLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tableoutbound1 = new javax.swing.JTable();
        Daritgl = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        DariKe = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btnsearchreceiving = new javax.swing.JButton();
        btnoutbound = new javax.swing.JButton();
        btnproduct = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        radiobtnReceiving = new javax.swing.JRadioButton();
        radiobtnOutbound = new javax.swing.JRadioButton();
        txtsuplier = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtproduct = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtKeuntungan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPengeluaran = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuLaporan = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuProductParent = new javax.swing.JMenu();
        MenuProduct = new javax.swing.JMenuItem();
        MenuProductMasuk = new javax.swing.JMenuItem();
        MenuProductKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laporan");
        jLabel1.setToolTipText("");

        Tableoutbound1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tableoutbound1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Tableoutbound1);

        Daritgl.setDateFormatString("yyyy-MM-dd");
        Daritgl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Dari");

        DariKe.setDateFormatString("yyyy-MM-dd");
        DariKe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ke");

        btnsearchreceiving.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsearchreceiving.setText("Receiving");
        btnsearchreceiving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchreceivingActionPerformed(evt);
            }
        });

        btnoutbound.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnoutbound.setText("OutBound");
        btnoutbound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoutboundActionPerformed(evt);
            }
        });

        btnproduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnproduct.setText("Product");
        btnproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        radiobtnReceiving.setText("Receiving");
        radiobtnReceiving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnReceivingActionPerformed(evt);
            }
        });

        radiobtnOutbound.setText("Outbound");

        txtsuplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Supplier ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pengecualian");

        jRadioButton1.setText("Product");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Perhatian : Jika anda mencari suplier dan product");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText(" pastikan dicheck list !!!");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Product ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jRadioButton1)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiobtnReceiving)
                            .addComponent(radiobtnOutbound))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsuplier)
                            .addComponent(txtproduct, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(radiobtnReceiving))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtsuplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(radiobtnOutbound)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Total :");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setText("Keuntungan :");

        jLabel11.setText("Pengeluaran : ");

        MenuLaporan.setText("File");
        MenuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaporanActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Laporan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuLaporan.add(jMenuItem1);

        jMenuBar2.add(MenuLaporan);

        MenuProductParent.setText("Product");
        MenuProductParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductParentActionPerformed(evt);
            }
        });

        MenuProduct.setText("Product");
        MenuProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductActionPerformed(evt);
            }
        });
        MenuProductParent.add(MenuProduct);

        MenuProductMasuk.setText("Product Masuk");
        MenuProductMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductMasukActionPerformed(evt);
            }
        });
        MenuProductParent.add(MenuProductMasuk);

        MenuProductKeluar.setText("Product Keluar");
        MenuProductKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductKeluarActionPerformed(evt);
            }
        });
        MenuProductParent.add(MenuProductKeluar);

        jMenuBar2.add(MenuProductParent);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnsearchreceiving, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(btnoutbound))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Daritgl, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 51, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DariKe, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtKeuntungan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DariKe, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Daritgl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtKeuntungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsearchreceiving)
                            .addComponent(btnoutbound)
                            .addComponent(btnproduct)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProduct().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaporanActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormLaporan().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuLaporanActionPerformed

    private void MenuProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProduct().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuProductActionPerformed

    private void MenuProductMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductMasukActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProductMasuk().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuProductMasukActionPerformed

    private void MenuProductKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductKeluarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProductKeluar().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuProductKeluarActionPerformed

    private void MenuProductParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductParentActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProductKeluar().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuProductParentActionPerformed

    private void radiobtnReceivingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnReceivingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnReceivingActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void receiving_table(){
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Product");
    model.addColumn("Nama Product");
    model.addColumn("Brand");
    model.addColumn("Jenis");
    model.addColumn("Harga");
    model.addColumn("Supplier");
    model.addColumn("Tanggal");
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(Daritgl.getDate());
    String Ke = dateFormat.format(DariKe.getDate());
        
    int var =1;
    try{
            String sql = "SELECT `kode_product`, `nama_product`, `brand_product`, `jenis_product`, `harga_product`, `status_product`, `qty_product`, `suplier`, `tgl_masuk` FROM `pemasukan` WHERE `tgl_masuk` BETWEEN '"+Dari+"' AND '"+Ke+"'";
            Connection koneksi = KoneksiDB.ConnectDb();
            PreparedStatement proses = koneksi.prepareStatement(sql);
            ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(1),hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6),hasil.getString(7)});
                
                }
            Tableoutbound1.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void total_mmasuk(){
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(Daritgl.getDate());
    String Ke = dateFormat.format(DariKe.getDate());
    
     try{
            String sql = "SELECT SUM(qty_product) FROM pemasukan WHERE tgl_masuk BETWEEN '"+Dari+"' AND '"+Ke+"'";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                txtTotal.setText(hasil.getString(1));
                
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
     
    }
    
    private void jasper_receiving(){
        koneksi = skripsi_andi.KoneksiDB.ConnectDb();
            try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String Dari = dateFormat.format(Daritgl.getDate());
            String Ke = dateFormat.format(DariKe.getDate());  
                HashMap param = new HashMap();
                    param.put("Dari",Dari);
                    param.put("Ke",Ke);
                    
                JasperPrint jp = JasperFillManager.fillReport("src/print/receiving.jasper", param , koneksi);
                    JRViewer jasperViewer = new JRViewer(jp);
                    JasperViewer jv=new JasperViewer(jp,false);
                    jv.setVisible(true);
            } catch(JRException e) {
                JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
            }
    }
    private void btnsearchreceivingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchreceivingActionPerformed
        // TODO add your handling code here:
        receiving_table();
        total_mmasuk();
        jasper_receiving();
    }//GEN-LAST:event_btnsearchreceivingActionPerformed
    
    private void outbound_table(){
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Product");
    model.addColumn("Nama Product");
    model.addColumn("Kode Surat Jalan");
    model.addColumn("Qty");
    model.addColumn("Kurir");
    model.addColumn("Biaya");
    model.addColumn("Tanggal");
    model.addColumn("Penerima");
    model.addColumn("Tujuan");
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(Daritgl.getDate());
    String Ke = dateFormat.format(DariKe.getDate());
        
    int var =1;
    try{
            String sql = "SELECT `kode_product`, `nama_product`, `kode_surat_jalan`, `qty_product`, `kurir`, `biaya`, `tgl_keluar`, `penerima`, `Tujuan` FROM `pengeluaran` WHERE `tgl_keluar` BETWEEN '"+Dari+"' AND '"+Ke+"'";
            Connection koneksi = KoneksiDB.ConnectDb();
            PreparedStatement proses = koneksi.prepareStatement(sql);
            ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(1),hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6),hasil.getString(7),hasil.getString(8),hasil.getString(9)});
                
                }
            Tableoutbound1.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    private void keuntungan_outbound(){
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(Daritgl.getDate());
    String Ke = dateFormat.format(DariKe.getDate());
    
     try{
            String sql = "SELECT SUM(harga_product) FROM pengeluaran WHERE tgl_keluar BETWEEN '"+Dari+"' AND '"+Ke+"'";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                txtKeuntungan.setText(hasil.getString(1));
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
    
    private void total_outbound(){
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(Daritgl.getDate());
    String Ke = dateFormat.format(DariKe.getDate());
    
     try{
            String sql = "SELECT COUNT(harga_product) FROM pengeluaran WHERE tgl_keluar BETWEEN '"+Dari+"' AND '"+Ke+"'";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                txtTotal.setText(hasil.getString(1));
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }
    }
    private void pengeluaran_outbound(){
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(Daritgl.getDate());
    String Ke = dateFormat.format(DariKe.getDate());
    
     try{
            String sql = "SELECT SUM(biaya) FROM surat_jalan WHERE tgl_keluar BETWEEN '"+Dari+"' AND '"+Ke+"'";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                txtPengeluaran.setText(hasil.getString(1));
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }    
    }
    private void jasper_outbound(){
        koneksi = skripsi_andi.KoneksiDB.ConnectDb();
            try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String Dari = dateFormat.format(Daritgl.getDate());
            String Ke = dateFormat.format(DariKe.getDate());  
                HashMap param = new HashMap();
                    param.put("Dari",Dari);
                    param.put("Ke",Ke);
                    
                JasperPrint jp = JasperFillManager.fillReport("src/print/outbound.jasper", param , koneksi);
                    JRViewer jasperViewer = new JRViewer(jp);
                    JasperViewer jv=new JasperViewer(jp,false);
                    jv.setVisible(true);
            } catch(JRException e) {
                JOptionPane.showMessageDialog(null,e );
            }
    }
    
    private void btnoutboundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoutboundActionPerformed
        // TODO add your handling code here:
        keuntungan_outbound();
        outbound_table();
        pengeluaran_outbound();
        total_outbound();
        jasper_outbound();
    }//GEN-LAST:event_btnoutboundActionPerformed

    private void product_table(){
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Kode Product");
    model.addColumn("Nama Product");
    model.addColumn("Status");
    model.addColumn("Brand");
    model.addColumn("Jenis");
    model.addColumn("Harga");
    model.addColumn("Qty");
    model.addColumn("Kode surat Jalan");
    model.addColumn("Supplier");
    model.addColumn("Tanggal");
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(Daritgl.getDate());
    String Ke = dateFormat.format(DariKe.getDate());
        
    int var =1;
    try{
            String sql = "SELECT `kode_product`, `nama_product`, `brand_product`, `jenis_product`, `harga_product`, `qty_product`, `status_product`, `supplier`, `tgl_dibuat` FROM `product` WHERE `tgl_dibuat` BETWEEN '"+Dari+"' AND '"+Ke+"'";
            Connection koneksi = KoneksiDB.ConnectDb();
            PreparedStatement proses = koneksi.prepareStatement(sql);
            ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(1),hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6),hasil.getString(7),hasil.getString(8),hasil.getString(9)});
                
                }
            Tableoutbound1.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void total_product(){
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String Dari = dateFormat.format(Daritgl.getDate());
    String Ke = dateFormat.format(DariKe.getDate());
    
     try{
            String sql = "SELECT SUM(qty_product) FROM product WHERE tgl_dibuat BETWEEN '"+Dari+"' AND '"+Ke+"'";
        Connection koneksi = KoneksiDB.ConnectDb();
        PreparedStatement proses = koneksi.prepareStatement(sql);
        ResultSet hasil = proses.executeQuery(sql);
            while(hasil.next()){
                txtTotal.setText(hasil.getString(1));
                }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL KONEKSI!");
        }    
    }
    
    private void jasper_product(){
        koneksi = skripsi_andi.KoneksiDB.ConnectDb();
            try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String Dari = dateFormat.format(Daritgl.getDate());
            String Ke = dateFormat.format(DariKe.getDate());  
                HashMap param = new HashMap();
                    param.put("Dari",Dari);
                    param.put("Ke",Ke);
                    
                JasperPrint jp = JasperFillManager.fillReport("src/print/product.jasper", param , koneksi);
                    JRViewer jasperViewer = new JRViewer(jp);
                    JasperViewer jv=new JasperViewer(jp,false);
                    jv.setVisible(true);
            } catch(JRException e) {
                JOptionPane.showMessageDialog(null,e );
            }
    }
    
    private void btnproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductActionPerformed
        // TODO add your handling code here:
        product_table();
        total_product();
        jasper_product();
    }//GEN-LAST:event_btnproductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DariKe;
    private com.toedter.calendar.JDateChooser Daritgl;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JMenuItem MenuProduct;
    private javax.swing.JMenuItem MenuProductKeluar;
    private javax.swing.JMenuItem MenuProductMasuk;
    private javax.swing.JMenu MenuProductParent;
    private javax.swing.JTable Tableoutbound1;
    private javax.swing.JButton btnoutbound;
    private javax.swing.JButton btnproduct;
    private javax.swing.JButton btnsearchreceiving;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton radiobtnOutbound;
    private javax.swing.JRadioButton radiobtnReceiving;
    private javax.swing.JTextField txtKeuntungan;
    private javax.swing.JTextField txtPengeluaran;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtproduct;
    private javax.swing.JTextField txtsuplier;
    // End of variables declaration//GEN-END:variables
}
