/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi_andi;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import static java.time.LocalTime.now;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FormProduct extends javax.swing.JFrame {
    Connection koneksi;
    ResultSet hasil;
    PreparedStatement proses;
    /**
     * Creates new form FormProduct
     */
    public FormProduct() {
        initComponents();
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtbrand = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcategory = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableProduct = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuLaporan = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuProductParent = new javax.swing.JMenu();
        MenuProduct = new javax.swing.JMenuItem();
        MenuProductMasuk = new javax.swing.JMenuItem();
        MenuProductKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product");

        txtkode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kode");

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama");

        txtbrand.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Brand");

        txtcategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Category");

        txtharga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtharga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txthargaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txthargaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txthargaMousePressed(evt);
            }
        });
        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        txtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthargaKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Harga");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("QTY");

        txtqty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        TableProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableProduct);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        MenuLaporan.setText("File");
        MenuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaporanActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Laporan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuLaporan.add(jMenuItem1);

        jMenuBar2.add(MenuLaporan);

        MenuProductParent.setText("Product");
        MenuProductParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductParentActionPerformed(evt);
            }
        });

        MenuProduct.setText("Product");
        MenuProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductActionPerformed(evt);
            }
        });
        MenuProductParent.add(MenuProduct);

        MenuProductMasuk.setText("Product Masuk");
        MenuProductMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductMasukActionPerformed(evt);
            }
        });
        MenuProductParent.add(MenuProductMasuk);

        MenuProductKeluar.setText("Product Keluar");
        MenuProductKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductKeluarActionPerformed(evt);
            }
        });
        MenuProductParent.add(MenuProductKeluar);

        jMenuBar2.add(MenuProductParent);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(43, 43, 43)
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(43, 43, 43)
                                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(43, 43, 43)
                                .addComponent(txtbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(53, 53, 53)
                                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(43, 43, 43)
                                        .addComponent(txtcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(43, 43, 43)
                                .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2)))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormLaporan().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaporanActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormLaporan().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuLaporanActionPerformed

    private void MenuProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProduct().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuProductActionPerformed

    private void MenuProductMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductMasukActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProductMasuk().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuProductMasukActionPerformed

    private void MenuProductKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductKeluarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProductKeluar().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuProductKeluarActionPerformed

    private void MenuProductParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductParentActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProductKeluar().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuProductParentActionPerformed

    private void TableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProductMouseClicked
        // TODO add your handling code here:
        int selectedRow = TableProduct.getSelectedRow();

    }//GEN-LAST:event_TableProductMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked
    
    public void getData( ){
     DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Product");
        model.addColumn("Nama Product");
        model.addColumn("Brand Product");
        model.addColumn("Category");
        model.addColumn("Harga");
        model.addColumn("QTY");
    
    try{
            String sql = "SELECT * FROM product";
            koneksi = KoneksiDB.ConnectDb();
            proses = koneksi.prepareStatement(sql);
            hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6),hasil.getString(7)});
                
                }
            TableProduct.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL Menampilkan ke table!");
        }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection koneksi = null;
        Statement stmt = null;
        try {
            LocalDateTime now = LocalDateTime.now();
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String tglbuat = now.format(formatter);
            
            koneksi = KoneksiDB.ConnectDb();
            stmt = koneksi.createStatement();
            stmt.executeUpdate("INSERT INTO `product`(`kode_product`, `nama_product`, `brand_product`, `jenis_product`, `harga_product`, `qty_product`, `tgl_dibuat`,status_product) VALUES ('"+txtkode.getText()+"','"+txtnama.getText()+"','"+txtbrand.getText()+"','"+txtcategory.getText()+"','"+txtharga.getText()+"','"+txtqty.getText()+"','"+tglbuat+"','Readytosell')");
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
        }
        getData();            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtkode.setText("");
        txtnama.setText("");
        txtbrand.setText("");
        txtcategory.setText("");
        txtqty.setText("");
        txtharga.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txthargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaKeyPressed
        
    }//GEN-LAST:event_txthargaKeyPressed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txthargaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthargaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaMouseEntered

    private void txthargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthargaMouseClicked
        // TODO add your handling code here:
        Connection koneksi = null;
        Statement stmt = null;
        try {
            LocalDateTime now = LocalDateTime.now();
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String tglbuat = now.format(formatter);
            
            koneksi = KoneksiDB.ConnectDb();
            stmt = koneksi.createStatement();
            stmt.executeUpdate("INSERT INTO `product`(`kode_product`, `nama_product`, `brand_product`, `jenis_product`, `harga_product`, `qty_product`, `tgl_dibuat`,status_product) VALUES ('"+txtkode.getText()+"','"+txtnama.getText()+"','"+txtbrand.getText()+"','"+txtcategory.getText()+"','"+txtharga.getText()+"','"+txtqty.getText()+"','"+tglbuat+"','Readytosell')");
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
        }
        getData();
    }//GEN-LAST:event_txthargaMouseClicked

    private void txthargaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthargaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaMousePressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        Connection koneksi = null;
        Statement stmt = null;
        try {
            LocalDateTime now = LocalDateTime.now();

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String tglbuat = now.format(formatter);

            koneksi = KoneksiDB.ConnectDb();
            stmt = koneksi.createStatement();
            stmt.executeUpdate("INSERT INTO `product`(`kode_product`, `nama_product`, `brand_product`, `jenis_product`, `harga_product`, `qty_product`, `tgl_dibuat`,status_product) VALUES ('"+txtkode.getText()+"','"+txtnama.getText()+"','"+txtbrand.getText()+"','"+txtcategory.getText()+"','"+txtharga.getText()+"','"+txtqty.getText()+"','"+tglbuat+"','Readytosell')");
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
        }
        getData();        
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        txtkode.setText("");
        txtnama.setText("");
        txtbrand.setText("");
        txtcategory.setText("");
        txtqty.setText("");
        txtharga.setText("");
    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JMenuItem MenuProduct;
    private javax.swing.JMenuItem MenuProductKeluar;
    private javax.swing.JMenuItem MenuProductMasuk;
    private javax.swing.JMenu MenuProductParent;
    private javax.swing.JTable TableProduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtbrand;
    private javax.swing.JTextField txtcategory;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables
}
