/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsi_andi;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FormProductMasuk extends javax.swing.JFrame {
        Connection koneksi;
        ResultSet hasil;
        PreparedStatement proses;
    /**
     * Creates new form FormProductMasuk
     */
    public FormProductMasuk() {
        initComponents();
        getData( );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtkodepro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtbrand = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcategory = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsupplier = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablereceiving = new javax.swing.JTable();
        btnsubmit = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuLaporan = new javax.swing.JMenuItem();
        MenuProductParent = new javax.swing.JMenu();
        MenuProduct = new javax.swing.JMenuItem();
        MenuProductMasuk = new javax.swing.JMenuItem();
        MenuProductKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Receiving");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Kode Product");

        txtkodepro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nama");

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtbrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Brand");

        txtcategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Category");

        txtqty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Qty");

        txtsupplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Supplier");

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        Tablereceiving.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tablereceiving.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tablereceiving.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablereceivingMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tablereceiving);

        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        btnsubmit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnsubmitKeyPressed(evt);
            }
        });

        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnedit.setText("EDIT");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Harga");

        txtharga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        MenuFile.setText("File");
        MenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileActionPerformed(evt);
            }
        });

        MenuLaporan.setText("Laporan");
        MenuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaporanActionPerformed(evt);
            }
        });
        MenuFile.add(MenuLaporan);

        jMenuBar2.add(MenuFile);

        MenuProductParent.setText("Product");
        MenuProductParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductParentActionPerformed(evt);
            }
        });

        MenuProduct.setText("Product");
        MenuProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductActionPerformed(evt);
            }
        });
        MenuProductParent.add(MenuProduct);

        MenuProductMasuk.setText("Product Masuk");
        MenuProductMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductMasukActionPerformed(evt);
            }
        });
        MenuProductParent.add(MenuProductMasuk);

        MenuProductKeluar.setText("Product Keluar");
        MenuProductKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductKeluarActionPerformed(evt);
            }
        });
        MenuProductParent.add(MenuProductKeluar);

        jMenuBar2.add(MenuProductParent);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnreset)
                .addGap(14, 14, 14)
                .addComponent(btnedit)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkodepro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkodepro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsubmit)
                    .addComponent(btnreset)
                    .addComponent(btnedit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaporanActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormLaporan().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuLaporanActionPerformed

    private void MenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileActionPerformed

    }//GEN-LAST:event_MenuFileActionPerformed

    private void MenuProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductActionPerformed
     
    }//GEN-LAST:event_MenuProductActionPerformed

    private void MenuProductMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductMasukActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProductMasuk().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuProductMasukActionPerformed

    private void MenuProductKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductKeluarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProductKeluar().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuProductKeluarActionPerformed

    private void MenuProductParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductParentActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    new FormProductKeluar().setVisible(true);
                    dispose();
                }
            });
    }//GEN-LAST:event_MenuProductParentActionPerformed

    private void TablereceivingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablereceivingMouseClicked
        int selectedRow = Tablereceiving.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)Tablereceiving.getModel();
        txtkodepro.setText(model.getValueAt(selectedRow, 0).toString());
        txtnama.setText(model.getValueAt(selectedRow, 1).toString());
        txtbrand.setText(model.getValueAt(selectedRow, 2).toString());
        txtcategory.setText(model.getValueAt(selectedRow, 3).toString());
        txtqty.setText(model.getValueAt(selectedRow, 6).toString());
        txtharga.setText(model.getValueAt(selectedRow, 4).toString());
        txtsupplier.setText(model.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_TablereceivingMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtkodepro.setText("");
        txtnama.setText("");
        txtbrand.setText("");
        txtcategory.setText("");
        txtqty.setText("");
        txtsupplier.setText("");
        txtharga.setText("");
    }//GEN-LAST:event_btnresetActionPerformed
    
    public void getData( ){
     DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Product");
        model.addColumn("Nama Product");
        model.addColumn("Brand Product");
        model.addColumn("Category");
        model.addColumn("Harga");
        model.addColumn("Supplier");
        model.addColumn("QTY");
        
    
    try{
            String sql = "SELECT * FROM pemasukan";
            koneksi = KoneksiDB.ConnectDb();
            proses = koneksi.prepareStatement(sql);
            hasil = proses.executeQuery(sql);
            while(hasil.next()){
                model.addRow(new Object[]{hasil.getString(2),hasil.getString(3),hasil.getString(4),hasil.getString(5),hasil.getString(6),hasil.getString(9),hasil.getString(8)});
                
                }
            Tablereceiving.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "GAGAL Menampilkan ke table!");
        }
    }
    
    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        Connection koneksi = null;
        Statement stmt = null;
        try {
            LocalDateTime now = LocalDateTime.now();
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String tglbuat = now.format(formatter);
            
            koneksi = KoneksiDB.ConnectDb();
            stmt = koneksi.createStatement();
            stmt.executeUpdate("INSERT INTO `pemasukan`(`kode_product`, `nama_product`, `brand_product`, `jenis_product`, `harga_product`, `qty_product`,`suplier`, `tgl_masuk`,status_product) VALUES ('"+txtkodepro.getText()+"','"+txtnama.getText()+"','"+txtbrand.getText()+"','"+txtcategory.getText()+"','"+txtharga.getText()+"','"+txtqty.getText()+"','"+txtsupplier.getText()+"','"+tglbuat+"','BarangMasuk')");
            stmt.executeUpdate("INSERT INTO `product`(`kode_product`, `nama_product`, `brand_product`, `jenis_product`, `harga_product`, `qty_product`,`supplier`, `tgl_dibuat`,status_product) VALUES ('"+txtkodepro.getText()+"','"+txtnama.getText()+"','"+txtbrand.getText()+"','"+txtcategory.getText()+"','"+txtharga.getText()+"','"+txtqty.getText()+"','"+txtsupplier.getText()+"','"+tglbuat+"','Supplier')");
//            System.out.println(Tets);
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
        }
        getData();
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnsubmitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnsubmitKeyPressed
        // TODO add your handling code here:
        Connection koneksi = null;
        Statement stmt = null;
        try {
            LocalDateTime now = LocalDateTime.now();
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String tglbuat = now.format(formatter);
            
            koneksi = KoneksiDB.ConnectDb();
            stmt = koneksi.createStatement();
            stmt.executeUpdate("INSERT INTO `pemasukan`(`kode_product`, `nama_product`, `brand_product`, `jenis_product`, `harga_product`, `qty_product`,`suplier`, `tgl_masuk`,status_product) VALUES ('"+txtkodepro.getText()+"','"+txtnama.getText()+"','"+txtbrand.getText()+"','"+txtcategory.getText()+"','"+txtharga.getText()+"','"+txtqty.getText()+"','"+txtsupplier.getText()+"','"+tglbuat+"','BarangMasuk')");
            stmt.executeUpdate("INSERT INTO `product`(`kode_product`, `nama_product`, `brand_product`, `jenis_product`, `harga_product`, `qty_product`,`supplier`, `tgl_dibuat`,status_product) VALUES ('"+txtkodepro.getText()+"','"+txtnama.getText()+"','"+txtbrand.getText()+"','"+txtcategory.getText()+"','"+txtharga.getText()+"','"+txtqty.getText()+"','"+txtsupplier.getText()+"','"+tglbuat+"','Supplier')");
//            System.out.println(Tets);
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI TAMBAHKAN KE DATABASE!");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "DATA GAGAL DITAMBAHKAN");
        }
        getData();
    }//GEN-LAST:event_btnsubmitKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProductMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProductMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProductMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProductMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProductMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem MenuLaporan;
    private javax.swing.JMenuItem MenuProduct;
    private javax.swing.JMenuItem MenuProductKeluar;
    private javax.swing.JMenuItem MenuProductMasuk;
    private javax.swing.JMenu MenuProductParent;
    private javax.swing.JTable Tablereceiving;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtbrand;
    private javax.swing.JTextField txtcategory;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkodepro;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsupplier;
    // End of variables declaration//GEN-END:variables
}
